---

version: "3.3"
services:
  prom2tower:
    build:
      context: .
      dockerfile: Dockerfile
    image: prom2tower
    #image: 4216808/prom2tower-awx
    container_name: prom2tower
    hostname: prom2tower  
    networks:
      - monitor-net
    depends_on:
      - alertmanager
    expose:
      - 9999
    volumes:
      - ${PWD}/config.yaml:/usr/local/etc/config.yaml
    restart: unless-stopped

